Medicio/Models/Doctor.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Medicio.Models
{
    public class Doctor
    {
        public int Id { get; set; }
        public string? Fullname { get; set; }
        public string? Position { get; set; }
        public string? Image { get; set; }
        [NotMapped]
        public IFormFile? FormFile { get; set; }
        public List<Icon>? Icons { get; set; }
    }
}

Medicio/Areas/admin/Controllers/DoctorsController.cs
using Medicio.DAL;
using Medicio.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Medicio.Areas.admin.Controllers
{
    [Area("admin")]
    [Authorize(Roles = "admin")]
    public class DoctorsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public DoctorsController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        public IActionResult Index()
        {
            var doctors = _context.Doctors.ToList();
            return View(doctors);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Doctor doctor)
        {
            if (!ModelState.IsValid) return View(doctor);
            if (doctor.FormFile is not null)
            {
                string imageName = Guid.NewGuid() + doctor.FormFile.FileName;
                string path = Path.Combine(_env.WebRootPath, "assets/img/doctors", imageName);
                using (FileStream fileStream = new FileStream(path, FileMode.Create))
                {
                    doctor.FormFile.CopyTo(fileStream);
                }
                doctor.Image = imageName;
                await _context.Doctors.AddAsync(doctor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(doctor);
        }
        public IActionResult Edit(int id)
        {
            var existDoctor = _context.Doctors.Find(id);
            if (existDoctor is null) return RedirectToAction(nameof(Index));
            return View(existDoctor);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Doctor doctor)
        {
            var existDoctor = _context.Doctors.Find(doctor.Id);
            if (doctor.FormFile is not null)
            {
                string imageName = Guid.NewGuid() + doctor.FormFile.FileName;
                string path = Path.Combine(_env.WebRootPath, "assets/img/doctors", imageName);
                using (FileStream fileStream = new FileStream(path, FileMode.Create))
                {
                    doctor.FormFile.CopyTo(fileStream);
                }
                existDoctor.Image = imageName;
                existDoctor.Position = doctor.Position;
                existDoctor.Fullname = doctor.Fullname;
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(doctor);
        }
        public IActionResult Delete(int id)
        {
            var existDoctor = _context.Doctors.Find(id);
            if (existDoctor is null) return RedirectToAction(nameof(Index));
            _context.Doctors.Remove(existDoctor);   
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Medicio/Areas/admin/Views/Doctors/Create.cshtml
@{
    ViewData["Title"] = "Create";
}
@model Doctor

<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Fullname" >Fullname</label>
        <input class="form-control" asp-for="Fullname"  placeholder="Enter fullname">
    </div>
    <div class="form-group">
        <label asp-for="Position">Position</label>
        <input class="form-control" asp-for="Position" placeholder="Position">
    </div>
    <div class="form-group">
        <label asp-for="FormFile">Position</label>
        <input class="form-control" asp-for="FormFile" accept="image/*">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Medicio/Areas/admin/Views/Doctors/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
}
@model Doctor

<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Fullname">Fullname</label>
        <input class="form-control" asp-for="Fullname" placeholder="Enter fullname">
    </div>
    <div class="form-group">
        <label asp-for="Position">Position</label>
        <input class="form-control" asp-for="Position" placeholder="Position">
    </div>
    <div class="form-group">
        <label asp-for="FormFile">Position</label>
        <input class="form-control" asp-for="FormFile" accept="image/*">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Medicio/Areas/admin/Views/Doctors/Index.cshtml
@{
    ViewData["Title"] = "Index";
    int count = 1;
}
@model List<Doctor>
<a class="btn btn-outline-success" asp-controller="Doctors" asp-action="create" >Create</a>

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Fullname</th>
            <th scope="col">Position</th>
            <th scope="col">Image</th>
            <th scope="col">Options</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@count</th>
                <td>@item.Fullname</td>
                <td>@item.Position</td>
                <td>
                    <img src="~/assets/img/doctors/@item.Image">
                </td>
                <td>
                    <a class="btn btn-outline-info" asp-controller="Doctors" asp-action="Edit" asp-route-id="@item.Id" >Edit</a>
                    <a class="btn btn-outline-danger" asp-controller="Doctors" asp-action="Delete" asp-route-id="@item.Id" >Delete</a>
                </td>
            </tr>
            count++;
        }
    </tbody>
</table>