Medicio/Models/Setting.cs
namespace Medicio.Models
{
    public class Setting
    {
        public int Id { get; set; }
        public string? NameOfDoctorsSection { get; set; }
        public string? TitleOfDoctorsSection { get; set; }
    }
}

Medicio/Areas/admin/Controllers/SettingsController.cs
using Medicio.DAL;
using Medicio.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Medicio.Areas.admin.Controllers
{
    [Area("admin")]
    [Authorize(Roles = "admin")]

    public class SettingsController : Controller
    {
        
        private readonly AppDbContext _context;

        public SettingsController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var settings = _context.Settings.ToList();
            return View(settings);
        }
        public IActionResult Edit(int id)
        {
            var setting = _context.Settings.Find(id);
            if (setting is null) return RedirectToAction(nameof(Index));
            return View(setting);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Setting setting)
        {
            var existSetting = _context.Settings.Find(setting.Id);
            if (existSetting is null) return RedirectToAction(nameof(Index));
            existSetting.NameOfDoctorsSection = setting.NameOfDoctorsSection;
            existSetting.TitleOfDoctorsSection = setting.TitleOfDoctorsSection;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Medicio/Areas/admin/Views/Settings/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
}

@model Setting

<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="NameOfDoctorsSection">Name</label>
        <input class="form-control" asp-for="NameOfDoctorsSection" placeholder="Enter name">
    </div>
    <div class="form-group">
        <label asp-for="TitleOfDoctorsSection">Title</label>
        <input class="form-control" asp-for="TitleOfDoctorsSection" placeholder="title">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Medicio/Areas/admin/Views/Settings/Index.cshtml
@{
    ViewData["Title"] = "Index";
    int count = 1;
}

@model List<Setting>

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name of team</th>
            <th scope="col">Title of team</th>
            <th scope="col">Options</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@count</th>
                <td>@item.NameOfDoctorsSection</td>
                <td>@item.TitleOfDoctorsSection</td>
                <td>
                    <a class="btn btn-outline-info" asp-controller="Settings" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                </td>
            </tr>
            count++;
        }
    </tbody>
</table>